config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :downloads
  resources :products
  resources :phones
  resources :posts2
  resources :posts do
    collection do
      get :surprise
    end
  end

  root 'posts#index'

  get 'locale', to: 'locales#save_locale', as: :set_locale

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/download.rb
class Download < ActiveRecord::Base
  after_create :fetch_body


  private
  def fetch_body
     PostFetchJob.perform_later(self)
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base

  before_create :dupa_wolowa
  before_create :piko_w_oko


  private
  def dupa_wolowa
    self.name = self.name.to_s.downcase
  end
  def piko_w_oko
    self.title = self.title.to_s.downcase
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  after_create :notify_admin
  before_create :titleize_author

  has_many :comments
  has_and_belongs_to_many :tags


  #validates :body, presence: true

  #scope :published, -> { where(author: true )}
  #scope :ordered, -> { order(created_at: :desc)}
  #scope :created_before, -> { where("created_at < ?" ) }



  mount_uploader :picture, PictureUploader   # korzystamy z dokumentacji z carrierwave
                                             # nasz atrybut w ktorym beda przechowywane sciezki do plikow to picture
                                             # a drugi argument to klasa PictureUploader


  def notify_admin
    PostsMailer.new_post_notification(self).deliver
  end

  private
  def titleize_author
   self.author = self.author.to_s.titleize
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  private
  def titleize_name
    self.name = self.name.to_s.titleize
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
  end

end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
    @downloads = Download.all
  end

  def new
    @download = Download.new
  end

  def create
    @download = Download.new(download_params)
    if @download.save
      flash[:notice] = "Dziekujemy za pobranie pliku"
    end
    redirect_to downloads_path
  end


  private
  def download_params
    params.require(:download).permit(:url, :body)
  end

end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  def save_locale
    session[:locale] = params[:locale]
    redirect_to :back
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:title, :name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.page(params[:page]).per(3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Dziekujemy za wpis"
          redirect_to posts_path
        end

      end
    end
  end

  def surprise

  end


  def post_params
    params.require(:post).permit(:author, :body, :picture)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/downloads/index.html.erb
<h1>Lista wpisów</h1>

<p class="lead">
  Witaj w pobierarce wpisów!
  <%= link_to "Dodaj własny wpis już teraz.", new_download_path %>
</p>

<table class="table table-striper">
  <thead>
  <th>URL</th>
  <th>Treść</th>
  </thead>
  <tbody>
  <% @downloads.each do |download| %>
      <tr>
        <td><%= download.url %></td>
        <td><%= simple_format(truncate(download.body, length: 250)) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/downloads/new.html.erb
<h1>Dodaj wpis do pobrania</h1>

<%= form_for @download do |f| %>
    <div class="form-group">
      <%= f.label :url, "Adres URL" %>
      <%= f.text_field :url, class: "form-control" %>
    </div>
    <%= f.submit "Dodaj wpis", class: "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuestBook</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
<% end %>


<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <%= t "index.select_language", language: I18n.locale %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "PL", set_locale_path(locale: "pl")%></li> <!-- i ta akcja bedzie pobierala z save_locale params - i znajduje sie w locales_controller  -->
    <li><%= link_to "EN", set_locale_path(locale: "en")%></li>
  </ul>
</div>


<div class="container">
  <div class="page-header">
    <h1>Ksiega gosci</h1>
  </div>
  <%= yield %>
</div>


<% if user_signed_in? %>
    <p><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %></p>
<% end %>


</body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuestBook</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
<% end %>
<div class="container">
  <div class="page-header">
    <h1>CRUD LAYOUT II</h1>
  </div>
  <%= yield %>
</div>


</body>
</html>

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing Phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Phones</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @phones.each do |phone| %>

        <tr>
          <td><%= phone.title %></td>
          <td><%= phone.name %></td>
          <td><%= link_to 'Show', phone %></td>
          <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
          <td><%= link_to 'Destroy', phone, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>


  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

<p>


  <%= link_to "Beack to Guest Book", posts_path %>
</p>

app/views/phones/new.html.erb
<h1>New Phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<blockquote>
  <p>
    <strong>Title:</strong>
    <%= @phone.title %>
  </p>
</blockquote>

<p>
  <strong>Name:</strong>
  <%= @phone.name %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>

app/views/posts/_surprise_content.html.erb
<div class="jumbotron">
  <h1>Niespodzianka?</h1>
  <p> To jest fajna niespodzianka </p>
  <p><%= link_to "Sprawdz to", posts_path, class: "btn btn-lg btn-primary" %></p>
</div>

app/views/posts/create.js.erb
$("#form-container").hide(500, function() {
  $("#form-container").html("<div class=\"alert alert-success\">Dziekujemy za wpis!</p>");
  $("#form-container").show(500);
})

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <p class="lead">
      Witaj w naszej księdze gości!
      <%= link_to "Dodaj własny wpis już teraz.", new_post_path %>
    </p>
<% else %>
    <p class="lead">
      Musisz się zalogować, aby dodać wpis.
      <%= link_to "Zaloguj się", new_user_session_path %>
    </p>
<% end %>



<h1>W naszej apce mamy jeszcze inna sciezke <p class="lead"><%= link_to "Przetwarzanie asynchroniczne", downloads_path %> </p></h1>
<p>

</p>







<pre>
   <%= I18n.localize Time.now, format: :long %>
  <%= I18n.localize Time.now, format: :short %>
  <%= l Date.today, format: :short %>                     <!-- Tutaj formatujemy dzisiejsza date -->
  <%= number_with_delimiter(1123131232.1231231231) %>     <!-- Tutaj formatujemy liczbe, w jezyku amerykanskim tysiace od milionow miliardow oddziela sie kropka-->
  <%= number_to_currency 1254.4444444 %>                  <!-- Ta metoda formatuje dane jako walute w zl lub usd -->
  <%= distance_of_time_in_words(rand(10_000).seconds) %>  <!-- A ta metoda to slowne odleglosc czasowa  -->
</pre>



<p class="lead">
  Witaj w naszej ksiedze gosci!
  <h1>
    <%= t "index.hello" %>
    <%= link_to "Dodaj wlsny wpis juz teraz", new_post_path %>
  </h1>
</p>


<div id="content-placeholder">
    <%= link_to "Niespodzianka", surprise_posts_path, class: "btn btn-info", remote: true %>
</div>



<% @posts.each do |post| %>
    <div class="row">
      <div class="col-md-4">
        <%= image_tag post.picture.url(:thumb) %>
      </div>
      <div class="col-md-8">
        <blockquote>
          <p><%= post.body %></p>
          <footer><cite><%= post.author %></cite></footer>
        </blockquote>
      </div>
    </div>
<% end %>


<p>
  <%= paginate @posts %>
</p>


<h4>
  <%= link_to "Phone", phones_path %>
</h4>

app/views/posts/new.html.erb
<h2>Dodawanie nowego wpisu</h2>

  <%= simple_form_for @post do |f| %>
      <%= f.input :author, hint: "Podaj swoje imie" %>
      <%= f.input :body, label: "Tresc", hint: "Tresc posta" %>
      <%= f.input :picture, label: "Obrazek" %>
      <%= f.submit class: "btn btn-defalut" %>
  <% end %>

app/views/posts/surprise.js.erb
$("#content-placeholder").html("<%= escape_javascript(render(partial: "surprise_content")) %>");

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>